### PR TITLE
OpenAPI Draft

### PR DESCRIPTION
**Pull request by Steven-N-Hart**
Please review this and let me know if we should post it.

### CODE REVIEW

**Comment by nhoffman** [comment]
@Steven-N-Hart - I think this is a great introduction to OpenAPI - I don't want to suggest anything that would create a barrier to publishing it, but a couple of questions to ponder, perhaps in a subsequent post:

- where does OpenAPI fit in the hierarchy of more familiar (to medical informatics) standards (LOINC, SNOMED, ICD, CPT, etc, etc) and formats (HL7, FHIR)? 
- in particular, is there any tension between choosing to use a more widely used communication standards like OpenAPI and FHIR? In contrast with FHIR (or HL7 for that matter), OpenAPI has little to say about content - in that respect, to what extent does use of OpenAPI actually support interoperability? Or would any application require an additional layer of standardization for content?

**Comment by Steven-N-Hart** [comment]
Thanks for the comments @nhoffman!

I think of OpenAPI as the first step in the hierarchy. One can use this standard as a way of *documenting* APIs that make them easier to work with.  The *contents* of each API should be tied to the relevant standards they are supporting (e.g. DICOM, HL7, etc.), so it will not conflict with other standards like DICOM & HL7. Also, because it is independent of those standards (and their constraints) , your APIs can be written to support different standards for different use cases. For example, you could easily imagine an API that retrieves a description about a LOINC code as a useful API. This isn't a use case for a DICOM protocol.

Right out of the box, you get the APIs described into the same set of sections, so it is relatively easy to know what it is doing and what the structure of the content it will return. As someone who has had to integrate systems with poorly/not documented APIs, I can assure you that this is a significant benefit that is not a heavy lift from the developer perspective.

Definitely a series of posts about each of these standards is warranted, and then we can show how they work together.

**Comment by nhoffman** [comment]
@Steven-N-Hart - with the next meeting coming up, perhaps this is a good time to publish this entry so that we can mention it as progress? I think it's great, and fits well within the stated scope of the project.

**Comment by Steven-N-Hart** [comment]
@gershkovich , do you concur?

**Comment by gershkovich** [comment]
I agree, we should publish this!

**Pull request merged**
